[project]
name = "frog-community-hub"
description = "FROG FT + faucet with 24h cooldown"
authors = []
telemetry = false

[contracts.frog-token-v3]
path = "contracts/frog-token-v3.clar"
clarity_version = 3
epoch = "latest"

[contracts.frog-dao-nft-v5]
path = "contracts/frog-dao-nft-v5.clar"
clarity_version = 3
epoch = "latest"

[repl]
costs_version = 2

[devnet]
