[project]
name = "frog-mvp"
description = "FROG FT + faucet with 24h cooldown"
authors = []
telemetry = false

[contracts.frog-token]
path = "contracts/frog-token.clar"
clarity_version = 3
epoch = "latest"

[contracts.frog-dao-nft]
path = "contracts/frog-dao-nft.clar"
clarity_version = 3
epoch = "latest"

[repl]
costs_version = 2

[devnet]
